package com.gromozeka.domain.model

import kotlinx.datetime.Instant
import kotlinx.serialization.Serializable

/**
 * Single reusable prompt fragment.
 *
 * Prompts are building blocks for agent system prompts.
 * Agent contains ordered list of prompt IDs that are assembled into final system prompt.
 *
 * This is an immutable value type - use copy() to create modified versions.
 *
 * @property id unique prompt identifier (hash of file path or generated for inline)
 * @property name human-readable prompt name (displayed in UI)
 * @property content markdown text of the prompt
 * @property type prompt location type with file path (or inline for dynamic prompts)
 * @property createdAt timestamp when prompt was created (immutable)
 * @property updatedAt timestamp of last modification
 */
@Serializable
data class Prompt(
    val id: Id,
    val name: String,
    val content: String,
    val type: Type,
    val createdAt: Instant,
    val updatedAt: Instant
) {
    /**
     * Unique prompt identifier (hash of file path or UUID for inline).
     */
    @Serializable
    @JvmInline
    value class Id(val value: String)

    /**
     * Prompt location type.
     * Type determines where prompt is stored and how its ID is resolved.
     * ID contains relative path specific to each type.
     */
    @Serializable
    sealed class Type {
        /**
         * Builtin prompt shipped with Gromozeka.
         * Stored in application resources.
         * ID format: "prompts/shared-base.md" (relative to resources/)
         */
        @Serializable
        object Builtin : Type()

        /**
         * Global prompt stored in user's home directory.
         * Available across all projects for this user.
         * ID format: "prompts/my-prompt.md" (relative to ~/.gromozeka/)
         */
        @Serializable
        object Global : Type()

        /**
         * Project-specific prompt stored in project directory.
         * Versioned with project code.
         * ID format: ".gromozeka/prompts/shared-base.md" (relative to project root)
         */
        @Serializable
        object Project : Type()

        /**
         * Environment information prompt generated dynamically.
         * Contains project path, platform info, git repo status, current date.
         * Generated by SystemPromptBuilder.buildEnvironmentInfo()
         * Not persisted to filesystem.
         */
        @Serializable
        object Environment : Type()
    }

    /**
     * Thrown when referenced prompt is not found.
     *
     * @property promptId ID of missing prompt
     */
    class NotFoundException(val promptId: Id) :
        Exception("Prompt not found: ${promptId.value}")
}
