/*
 * This file was generated by the Gradle 'init' task.
 * Modified for Kotlin MPP project.
 */

plugins {
    alias(libs.plugins.kotlin.multiplatform) apply false
    alias(libs.plugins.kotlin.spring) apply false
    alias(libs.plugins.kotlin.serialization) apply false
    alias(libs.plugins.kotlin.compose) apply false
    alias(libs.plugins.spring.boot) apply false
    alias(libs.plugins.spring.dependency.management) apply false
    alias(libs.plugins.jetbrains.compose) apply false
}

allprojects {
    group = "com.example"
    version = "0.0.1-SNAPSHOT"
}
