/*
 * This file was generated by the Gradle 'init' task.
 * Modified for Kotlin MPP project.
 */

import org.jetbrains.kotlin.gradle.tasks.KotlinCompilationTask

plugins {
    alias(libs.plugins.kotlin.multiplatform) apply false
    alias(libs.plugins.kotlin.spring) apply false
    alias(libs.plugins.kotlin.serialization) apply false
    alias(libs.plugins.kotlin.compose) apply false
    alias(libs.plugins.spring.boot) apply false
    alias(libs.plugins.spring.dependency.management) apply false
    alias(libs.plugins.jetbrains.compose) apply false
}

// Centralized experimental API opt-ins for all Kotlin modules
val experimentalOptIns = listOf(
    "kotlin.time.ExperimentalTime",
    "kotlinx.serialization.ExperimentalSerializationApi",
    "androidx.compose.material3.ExperimentalMaterial3Api",
    "androidx.compose.ui.ExperimentalComposeUiApi",
    "androidx.compose.foundation.ExperimentalFoundationApi"
)

// Centralized version for the entire project
val projectVersion = "1.4.7"

allprojects {
    group = "com.example"
    version = projectVersion

    // Apply experimental opt-ins to all Kotlin compilation tasks
    tasks.withType<KotlinCompilationTask<*>>().configureEach {
        compilerOptions {
            experimentalOptIns.forEach { optIn.add(it) }
        }
    }
}
