@file:OptIn(org.jetbrains.kotlin.gradle.ExperimentalWasmDsl::class)

/*
 * This file was generated by the Gradle 'init' task.
 * Modified for Kotlin MPP project.
 */

import org.jetbrains.kotlin.gradle.tasks.KotlinCompilationTask
import org.jetbrains.kotlin.gradle.targets.wasm.binaryen.BinaryenEnvSpec
import org.jetbrains.kotlin.gradle.targets.wasm.binaryen.BinaryenPlugin
import org.jetbrains.kotlin.gradle.targets.wasm.nodejs.WasmNodeJsEnvSpec
import org.jetbrains.kotlin.gradle.targets.wasm.nodejs.WasmNodeJsPlugin
import org.jetbrains.kotlin.gradle.targets.wasm.yarn.WasmYarnPlugin
import org.jetbrains.kotlin.gradle.targets.wasm.yarn.WasmYarnRootEnvSpec

plugins {
    alias(libs.plugins.kotlin.multiplatform) apply false
    alias(libs.plugins.kotlin.jvm) apply false
    alias(libs.plugins.kotlin.spring) apply false
    alias(libs.plugins.kotlin.serialization) apply false
    alias(libs.plugins.kotlin.compose) apply false
    alias(libs.plugins.android.application) apply false
    alias(libs.plugins.android.kotlin.multiplatform.library) apply false
    alias(libs.plugins.spring.boot) apply false
    alias(libs.plugins.spring.dependency.management) apply false
    alias(libs.plugins.jetbrains.compose) apply false
}

// Experimental API opt-ins shared by all Kotlin modules
val experimentalOptIns = listOf(
    "kotlin.time.ExperimentalTime",
    "kotlinx.serialization.ExperimentalSerializationApi"
)

val projectVersion = providers.gradleProperty("gromozeka.version")
    .orElse("0.0.0-dev")
    .get()

allprojects {
    group = "com.example"
    version = projectVersion

    // Apply experimental opt-ins to all Kotlin compilation tasks
    tasks.withType<KotlinCompilationTask<*>>().configureEach {
        compilerOptions {
            experimentalOptIns.forEach { optIn.add(it) }
        }
    }

    // Repositories for Kotlin/Wasm tooling are declared in settings.gradle.kts.
    // Nulling these URLs prevents the Kotlin plugin from adding project repositories.
    plugins.withType<WasmNodeJsPlugin> {
        extensions.configure<WasmNodeJsEnvSpec>(WasmNodeJsEnvSpec.EXTENSION_NAME) {
            downloadBaseUrl.unset()
        }
    }

    plugins.withType<WasmYarnPlugin> {
        extensions.configure<WasmYarnRootEnvSpec>(WasmYarnRootEnvSpec.YARN) {
            downloadBaseUrl.unset()
        }
    }

    plugins.withType<BinaryenPlugin> {
        extensions.configure<BinaryenEnvSpec>(BinaryenEnvSpec.EXTENSION_NAME) {
            downloadBaseUrl.unset()
        }
    }
}
