/*
 * This file was generated by the Gradle 'init' task.
 * Modified for Kotlin MPP project.
 */

rootProject.name = "gromozeka"

include(":shared")
include(":domain")
include(":application")
include(":infrastructure-db")
include(":infrastructure-ai")
include(":infrastructure-ai:tree-sitter-kotlin-grammar")
include(":presentation")

// Настройка репозиториев для всех проектов
dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    
    repositories {
        mavenCentral()
        google()
        maven { url = uri("https://repo.spring.io/milestone") }
        maven { url = uri("https://repo.spring.io/snapshot") }
        maven {
            name = "Central Portal Snapshots"
            url = uri("https://central.sonatype.com/repository/maven-snapshots/")
        }
        maven { url = uri("https://jitpack.io") }
    }
}
