package com.gromozeka.domain.model.memory

import kotlinx.datetime.Instant

/**
 * Entity node in the knowledge graph representing a named concept or object.
 *
 * Knowledge graph stores facts as entity-relationship triples: (Entity)-[Relationship]->(Entity).
 * This class represents entity nodes with semantic embeddings for similarity search.
 *
 * ## Temporal Model
 *
 * Entities support temporal tracking to model lifecycle of concepts:
 *
 * - **Transaction-time dimension:** [createdAt] - when entity was recorded in database
 * - **Valid-time dimension:** [validAt] / [invalidAt] - when entity was/is valid in reality
 *
 * **Use cases for temporal fields:**
 * - Obsolete concepts: "Phlogiston" (valid 1667-1770s, then disproved)
 * - Temporal events: "COVID-19 pandemic" (valid 2020-2023)
 * - Architectural decisions: "Microservices architecture Project X" (valid 2020-2026)
 * - Timeless concepts: "Kotlin", "Mathematics" (validAt = ALWAYS_VALID_FROM)
 *
 * ## Multi-tenancy
 * Entities are isolated by [groupId] to support multiple users/contexts.
 *
 * ## Semantic Search
 * [embedding] enables vector similarity search for finding related entities.
 * Embeddings are generated from entity name using text-embedding-3-large (3072 dimensions).
 *
 * This is an immutable value type - use copy() to create modified versions.
 *
 * @property uuid unique entity identifier (UUIDv4)
 * @property name entity name (e.g., "Gromozeka", "Kotlin", "Clean Architecture")
 * @property embedding vector representation of entity name for semantic search (3072 dimensions, nullable if not yet embedded)
 * @property summary human-readable description of the entity (generated by LLM, max ~250 chars)
 * @property groupId multi-tenancy identifier isolating entities per user/context (currently "dev-user")
 * @property labels entity type labels from entity-types.json (e.g., ["Technology"], ["Person"], ["Concept"])
 * @property createdAt timestamp when entity was recorded in database (transaction-time, immutable)
 * @property validAt timestamp when entity became valid in reality (valid-time start, defaults to ALWAYS_VALID_FROM for timeless concepts)
 * @property invalidAt timestamp when entity became invalid/obsolete (valid-time end, defaults to STILL_VALID for currently valid entities)
 * @property attributes extensible key-value storage for future metadata (currently unused)
 */
data class MemoryObject(
    val uuid: String,
    val name: String,
    val embedding: List<Float>?,
    val summary: String,
    val groupId: String,
    val labels: List<String>,
    val createdAt: Instant,
    val validAt: Instant = TemporalConstants.ALWAYS_VALID_FROM,
    val invalidAt: Instant = TemporalConstants.STILL_VALID,
    val attributes: Map<String, Any> = emptyMap()
)
