package com.gromozeka.domain.model.memory

import com.gromozeka.domain.model.memory.MemoryPredicateDefinition.AggregateEffect
import com.gromozeka.domain.model.memory.MemoryPredicateDefinition.SemanticKind

object MemoryPredicateCatalogDefaults {
    fun forNamespace(namespace: MemoryNamespace): MemoryPredicateCatalog =
        definitions.map { it.scopedTo(namespace) }

    private val definitions = listOf(
        definition(
            predicate = "preferred_name",
            description = "Preferred display name for the subject",
            subjectType = MemoryEntity.Type.PERSON,
            objectKind = MemoryPredicateDefinition.ObjectValueKind.STRING,
            cardinality = MemoryPredicateDefinition.Cardinality.SINGLE,
            temporalPolicy = MemoryPredicateDefinition.TemporalPolicy.ATEMPORAL,
            conflictPolicy = MemoryPredicateDefinition.ConflictPolicy.REPLACE,
            semanticKinds = setOf(SemanticKind.IDENTITY),
            profileSync = true,
            defaultImportance = 8,
        ),
        definition(
            predicate = "speaks_language",
            description = "Language known or used by the subject",
            subjectType = MemoryEntity.Type.PERSON,
            objectKind = MemoryPredicateDefinition.ObjectValueKind.STRING,
            cardinality = MemoryPredicateDefinition.Cardinality.MULTI,
            temporalPolicy = MemoryPredicateDefinition.TemporalPolicy.ATEMPORAL,
            conflictPolicy = MemoryPredicateDefinition.ConflictPolicy.COEXIST,
            semanticKinds = setOf(SemanticKind.LANGUAGE, SemanticKind.CAPABILITY),
            profileSync = true,
            defaultImportance = 7,
        ),
        definition(
            predicate = "timezone",
            description = "Timezone of the subject",
            subjectType = MemoryEntity.Type.PERSON,
            objectKind = MemoryPredicateDefinition.ObjectValueKind.STRING,
            cardinality = MemoryPredicateDefinition.Cardinality.SINGLE,
            temporalPolicy = MemoryPredicateDefinition.TemporalPolicy.STATUS_LIKE,
            conflictPolicy = MemoryPredicateDefinition.ConflictPolicy.REPLACE,
            semanticKinds = setOf(SemanticKind.TIMEZONE),
            profileSync = true,
            defaultImportance = 7,
        ),
        definition(
            predicate = "prefers_response_language",
            description = "Preferred language for assistant responses",
            subjectType = MemoryEntity.Type.PERSON,
            objectKind = MemoryPredicateDefinition.ObjectValueKind.STRING,
            cardinality = MemoryPredicateDefinition.Cardinality.SINGLE,
            temporalPolicy = MemoryPredicateDefinition.TemporalPolicy.STATUS_LIKE,
            conflictPolicy = MemoryPredicateDefinition.ConflictPolicy.REPLACE,
            semanticKinds = setOf(SemanticKind.PREFERENCE),
            profileSync = true,
            defaultImportance = 9,
        ),
        definition(
            predicate = "prefers_answer_detail",
            description = "Preferred answer detail level",
            subjectType = MemoryEntity.Type.PERSON,
            objectKind = MemoryPredicateDefinition.ObjectValueKind.STRING,
            cardinality = MemoryPredicateDefinition.Cardinality.SINGLE,
            temporalPolicy = MemoryPredicateDefinition.TemporalPolicy.STATUS_LIKE,
            conflictPolicy = MemoryPredicateDefinition.ConflictPolicy.REPLACE,
            semanticKinds = setOf(SemanticKind.PREFERENCE),
            profileSync = true,
            defaultImportance = 8,
        ),
        definition(
            predicate = "prefers_tone",
            description = "Preferred response tone",
            subjectType = MemoryEntity.Type.PERSON,
            objectKind = MemoryPredicateDefinition.ObjectValueKind.STRING,
            cardinality = MemoryPredicateDefinition.Cardinality.SINGLE,
            temporalPolicy = MemoryPredicateDefinition.TemporalPolicy.STATUS_LIKE,
            conflictPolicy = MemoryPredicateDefinition.ConflictPolicy.REPLACE,
            semanticKinds = setOf(SemanticKind.PREFERENCE),
            profileSync = true,
            defaultImportance = 7,
        ),
        definition(
            predicate = "prefers_code_comment_language",
            description = "Preferred language for code comments",
            subjectType = MemoryEntity.Type.PERSON,
            objectKind = MemoryPredicateDefinition.ObjectValueKind.STRING,
            cardinality = MemoryPredicateDefinition.Cardinality.SINGLE,
            temporalPolicy = MemoryPredicateDefinition.TemporalPolicy.STATUS_LIKE,
            conflictPolicy = MemoryPredicateDefinition.ConflictPolicy.REPLACE,
            semanticKinds = setOf(SemanticKind.PREFERENCE),
            profileSync = true,
            defaultImportance = 9,
        ),
        definition(
            predicate = "works_with",
            description = "Current or ongoing technology/tool usage",
            subjectType = MemoryEntity.Type.PERSON,
            objectKind = MemoryPredicateDefinition.ObjectValueKind.ENTITY,
            cardinality = MemoryPredicateDefinition.Cardinality.MULTI,
            temporalPolicy = MemoryPredicateDefinition.TemporalPolicy.STATUS_LIKE,
            conflictPolicy = MemoryPredicateDefinition.ConflictPolicy.COEXIST,
            semanticKinds = setOf(SemanticKind.CAPABILITY, SemanticKind.TECHNICAL_CONFIGURATION),
            profileSync = true,
            defaultImportance = 7,
        ),
        definition(
            predicate = "prefers",
            description = "Generic positive preference when no named current/default/primary/chosen slot predicate is more precise",
            subjectType = MemoryEntity.Type.PERSON,
            objectKind = MemoryPredicateDefinition.ObjectValueKind.ENTITY,
            cardinality = MemoryPredicateDefinition.Cardinality.MULTI,
            temporalPolicy = MemoryPredicateDefinition.TemporalPolicy.STATUS_LIKE,
            conflictPolicy = MemoryPredicateDefinition.ConflictPolicy.COEXIST,
            semanticKinds = setOf(SemanticKind.PREFERENCE),
            profileSync = true,
            defaultImportance = 7,
        ),
        definition(
            predicate = "avoids",
            description = "Negative preference, exclusion, or avoid instruction",
            objectKind = MemoryPredicateDefinition.ObjectValueKind.ENTITY,
            cardinality = MemoryPredicateDefinition.Cardinality.MULTI,
            temporalPolicy = MemoryPredicateDefinition.TemporalPolicy.STATUS_LIKE,
            conflictPolicy = MemoryPredicateDefinition.ConflictPolicy.COEXIST,
            semanticKinds = setOf(SemanticKind.AVOIDANCE),
            profileSync = true,
            defaultImportance = 7,
        ),
        definition(
            predicate = "believes",
            description = "Attributed belief, opinion, or viewpoint held by the subject",
            objectKind = MemoryPredicateDefinition.ObjectValueKind.STRING,
            cardinality = MemoryPredicateDefinition.Cardinality.MULTI,
            temporalPolicy = MemoryPredicateDefinition.TemporalPolicy.STATUS_LIKE,
            conflictPolicy = MemoryPredicateDefinition.ConflictPolicy.COEXIST,
            semanticKinds = setOf(SemanticKind.BELIEF),
            defaultImportance = 7,
        ),
        definition(
            predicate = "has_experience_with",
            description = "Experience with a technology or domain",
            subjectType = MemoryEntity.Type.PERSON,
            objectKind = MemoryPredicateDefinition.ObjectValueKind.ENTITY,
            cardinality = MemoryPredicateDefinition.Cardinality.MULTI,
            temporalPolicy = MemoryPredicateDefinition.TemporalPolicy.ATEMPORAL,
            conflictPolicy = MemoryPredicateDefinition.ConflictPolicy.COEXIST,
            semanticKinds = setOf(SemanticKind.CAPABILITY),
            profileSync = true,
            defaultImportance = 6,
        ),
        definition(
            predicate = "attended_event",
            description = "Subject attended or was present at a dated event, appointment, meeting, or gathering",
            subjectType = MemoryEntity.Type.PERSON,
            objectKind = MemoryPredicateDefinition.ObjectValueKind.STRING,
            cardinality = MemoryPredicateDefinition.Cardinality.MULTI,
            temporalPolicy = MemoryPredicateDefinition.TemporalPolicy.TIME_SCOPED,
            conflictPolicy = MemoryPredicateDefinition.ConflictPolicy.COEXIST,
            semanticKinds = setOf(SemanticKind.EVENT_PARTICIPATION),
            defaultImportance = 6,
        ),
        definition(
            predicate = "has_goal",
            description = "Active or declared goal",
            objectKind = MemoryPredicateDefinition.ObjectValueKind.STRING,
            cardinality = MemoryPredicateDefinition.Cardinality.MULTI,
            temporalPolicy = MemoryPredicateDefinition.TemporalPolicy.STATUS_LIKE,
            conflictPolicy = MemoryPredicateDefinition.ConflictPolicy.COEXIST,
            semanticKinds = setOf(SemanticKind.GOAL),
            profileSync = true,
            actionItemSync = true,
            defaultImportance = 8,
        ),
        definition(
            predicate = "current_metric_value",
            description = "Current value of a named metric, record, benchmark, score, quota, threshold, or personal best",
            objectKind = MemoryPredicateDefinition.ObjectValueKind.STRING,
            cardinality = MemoryPredicateDefinition.Cardinality.SINGLE,
            temporalPolicy = MemoryPredicateDefinition.TemporalPolicy.STATUS_LIKE,
            conflictPolicy = MemoryPredicateDefinition.ConflictPolicy.REPLACE,
            semanticKinds = setOf(SemanticKind.AGGREGATE_VALUE),
            aggregateEffect = AggregateEffect.SET_CURRENT_VALUE,
            defaultImportance = 8,
        ),
        definition(
            predicate = "metric_observation",
            description = "Explicit observed value of a named metric in a specific event, attempt, condition, measurement, or historical observation",
            objectKind = MemoryPredicateDefinition.ObjectValueKind.STRING,
            cardinality = MemoryPredicateDefinition.Cardinality.MULTI,
            temporalPolicy = MemoryPredicateDefinition.TemporalPolicy.TIME_SCOPED,
            conflictPolicy = MemoryPredicateDefinition.ConflictPolicy.COEXIST,
            semanticKinds = setOf(SemanticKind.AGGREGATE_VALUE),
            defaultImportance = 7,
        ),
        definition(
            predicate = "aggregate_increase",
            description = "Explicit positive numeric delta applied to a named countable aggregate, inventory, or collection; object is the positive amount added",
            objectKind = MemoryPredicateDefinition.ObjectValueKind.NUMBER,
            cardinality = MemoryPredicateDefinition.Cardinality.MULTI,
            temporalPolicy = MemoryPredicateDefinition.TemporalPolicy.TIME_SCOPED,
            conflictPolicy = MemoryPredicateDefinition.ConflictPolicy.COEXIST,
            semanticKinds = setOf(SemanticKind.AGGREGATE_DELTA),
            aggregateEffect = AggregateEffect.INCREASE,
            defaultImportance = 7,
        ),
        definition(
            predicate = "aggregate_decrease",
            description = "Explicit negative numeric delta applied to a named countable aggregate, inventory, or collection; object is the positive amount removed",
            objectKind = MemoryPredicateDefinition.ObjectValueKind.NUMBER,
            cardinality = MemoryPredicateDefinition.Cardinality.MULTI,
            temporalPolicy = MemoryPredicateDefinition.TemporalPolicy.TIME_SCOPED,
            conflictPolicy = MemoryPredicateDefinition.ConflictPolicy.COEXIST,
            semanticKinds = setOf(SemanticKind.AGGREGATE_DELTA),
            aggregateEffect = AggregateEffect.DECREASE,
            defaultImportance = 7,
        ),
        definition(
            predicate = "current_location",
            description = "Current physical residence, base, or location of a person, user, organization, project, or concrete subject",
            objectKind = MemoryPredicateDefinition.ObjectValueKind.JSON,
            cardinality = MemoryPredicateDefinition.Cardinality.SINGLE,
            temporalPolicy = MemoryPredicateDefinition.TemporalPolicy.STATUS_LIKE,
            conflictPolicy = MemoryPredicateDefinition.ConflictPolicy.REPLACE,
            semanticKinds = setOf(SemanticKind.LOCATION),
            profileSync = true,
            defaultImportance = 8,
        ),
        definition(
            predicate = "generated_artifact_detail",
            description = "Concrete reusable detail contained in an imported generated artifact, draft, story, image description, specification, or code artifact",
            objectKind = MemoryPredicateDefinition.ObjectValueKind.STRING,
            cardinality = MemoryPredicateDefinition.Cardinality.MULTI,
            temporalPolicy = MemoryPredicateDefinition.TemporalPolicy.ATEMPORAL,
            conflictPolicy = MemoryPredicateDefinition.ConflictPolicy.COEXIST,
            semanticKinds = setOf(SemanticKind.ARTIFACT_DETAIL),
            defaultImportance = 6,
        ),
        definition(
            predicate = "pending_pickup",
            description = "Subject needs to collect, pick up, retrieve, or receive a concrete item from a place or party",
            objectKind = MemoryPredicateDefinition.ObjectValueKind.STRING,
            cardinality = MemoryPredicateDefinition.Cardinality.MULTI,
            temporalPolicy = MemoryPredicateDefinition.TemporalPolicy.STATUS_LIKE,
            conflictPolicy = MemoryPredicateDefinition.ConflictPolicy.COEXIST,
            semanticKinds = setOf(SemanticKind.OBLIGATION),
            actionItemSync = true,
            defaultImportance = 8,
        ),
        definition(
            predicate = "pending_return",
            description = "Subject needs to return, send back, drop off, or bring back a concrete item to a place or party",
            objectKind = MemoryPredicateDefinition.ObjectValueKind.STRING,
            cardinality = MemoryPredicateDefinition.Cardinality.MULTI,
            temporalPolicy = MemoryPredicateDefinition.TemporalPolicy.STATUS_LIKE,
            conflictPolicy = MemoryPredicateDefinition.ConflictPolicy.COEXIST,
            semanticKinds = setOf(SemanticKind.OBLIGATION),
            actionItemSync = true,
            defaultImportance = 8,
        ),
        definition(
            predicate = "has_constraint",
            description = "Stable user or project constraint",
            objectKind = MemoryPredicateDefinition.ObjectValueKind.STRING,
            cardinality = MemoryPredicateDefinition.Cardinality.MULTI,
            temporalPolicy = MemoryPredicateDefinition.TemporalPolicy.STATUS_LIKE,
            conflictPolicy = MemoryPredicateDefinition.ConflictPolicy.COEXIST,
            semanticKinds = setOf(SemanticKind.CONSTRAINT),
            profileSync = true,
            defaultImportance = 8,
        ),
        definition(
            predicate = "owns",
            description = "Subject owns, keeps, possesses, has a personal copy of, or has in a collection a concrete physical or digital item",
            subjectType = MemoryEntity.Type.PERSON,
            objectKind = MemoryPredicateDefinition.ObjectValueKind.ENTITY,
            cardinality = MemoryPredicateDefinition.Cardinality.MULTI,
            temporalPolicy = MemoryPredicateDefinition.TemporalPolicy.STATUS_LIKE,
            conflictPolicy = MemoryPredicateDefinition.ConflictPolicy.COEXIST,
            semanticKinds = setOf(SemanticKind.POSSESSION),
            profileSync = true,
            defaultImportance = 7,
        ),
        definition(
            predicate = "responsible_for",
            description = "Subject is responsible for a workstream, component, process, account duty, or operational area",
            objectKind = MemoryPredicateDefinition.ObjectValueKind.ENTITY,
            cardinality = MemoryPredicateDefinition.Cardinality.MULTI,
            temporalPolicy = MemoryPredicateDefinition.TemporalPolicy.STATUS_LIKE,
            conflictPolicy = MemoryPredicateDefinition.ConflictPolicy.COEXIST,
            semanticKinds = setOf(SemanticKind.RESPONSIBILITY),
            profileSync = true,
            defaultImportance = 8,
        ),
        definition(
            predicate = "assigned_to_shift",
            description = "Person or agent assignment to a shift, schedule slot, day, route, or rotation cell",
            subjectType = MemoryEntity.Type.PERSON,
            objectKind = MemoryPredicateDefinition.ObjectValueKind.STRING,
            cardinality = MemoryPredicateDefinition.Cardinality.MULTI,
            temporalPolicy = MemoryPredicateDefinition.TemporalPolicy.TIME_SCOPED,
            conflictPolicy = MemoryPredicateDefinition.ConflictPolicy.COEXIST,
            semanticKinds = setOf(SemanticKind.ASSIGNMENT),
            defaultImportance = 7,
        ),
        definition(
            predicate = "works_on_project",
            description = "Association with a project when no more specific role, responsibility, ownership, or project-state predicate is available",
            subjectType = MemoryEntity.Type.PERSON,
            objectKind = MemoryPredicateDefinition.ObjectValueKind.ENTITY,
            cardinality = MemoryPredicateDefinition.Cardinality.MULTI,
            temporalPolicy = MemoryPredicateDefinition.TemporalPolicy.TIME_SCOPED,
            conflictPolicy = MemoryPredicateDefinition.ConflictPolicy.RANGE_SPLIT,
            semanticKinds = setOf(SemanticKind.PROJECT_ASSOCIATION),
            profileSync = true,
            actionItemSync = true,
            defaultImportance = 7,
        ),
        definition(
            predicate = "primary_storage_backend",
            description = "Primary storage or persistence backend for a project or service",
            subjectType = MemoryEntity.Type.PROJECT,
            objectKind = MemoryPredicateDefinition.ObjectValueKind.ENTITY,
            cardinality = MemoryPredicateDefinition.Cardinality.SINGLE,
            temporalPolicy = MemoryPredicateDefinition.TemporalPolicy.STATUS_LIKE,
            conflictPolicy = MemoryPredicateDefinition.ConflictPolicy.REPLACE,
            semanticKinds = setOf(SemanticKind.TECHNICAL_CONFIGURATION),
            defaultImportance = 8,
        ),
        definition(
            predicate = "uses_search_backend",
            description = "Search backend used by a project or service in a specific environment, phase, or time window",
            objectKind = MemoryPredicateDefinition.ObjectValueKind.ENTITY,
            cardinality = MemoryPredicateDefinition.Cardinality.SINGLE,
            temporalPolicy = MemoryPredicateDefinition.TemporalPolicy.TIME_SCOPED,
            conflictPolicy = MemoryPredicateDefinition.ConflictPolicy.RANGE_SPLIT,
            semanticKinds = setOf(SemanticKind.TECHNICAL_CONFIGURATION),
            defaultImportance = 7,
        ),
        definition(
            predicate = "uses_persistence_database",
            description = "Persistence database used by a project or service in a specific environment, phase, or time window",
            subjectType = MemoryEntity.Type.PROJECT,
            objectKind = MemoryPredicateDefinition.ObjectValueKind.ENTITY,
            cardinality = MemoryPredicateDefinition.Cardinality.MULTI,
            temporalPolicy = MemoryPredicateDefinition.TemporalPolicy.TIME_SCOPED,
            conflictPolicy = MemoryPredicateDefinition.ConflictPolicy.RANGE_SPLIT,
            semanticKinds = setOf(SemanticKind.TECHNICAL_CONFIGURATION),
            defaultImportance = 6,
        ),
        definition(
            predicate = "owns_vehicle",
            description = "Vehicle owned or used by the subject",
            subjectType = MemoryEntity.Type.PERSON,
            objectKind = MemoryPredicateDefinition.ObjectValueKind.ENTITY,
            cardinality = MemoryPredicateDefinition.Cardinality.MULTI,
            temporalPolicy = MemoryPredicateDefinition.TemporalPolicy.STATUS_LIKE,
            conflictPolicy = MemoryPredicateDefinition.ConflictPolicy.COEXIST,
            semanticKinds = setOf(SemanticKind.POSSESSION),
            profileSync = true,
            defaultImportance = 6,
        ),
        definition(
            predicate = "prefers_storage",
            description = "Preferred storage solution",
            subjectType = MemoryEntity.Type.PERSON,
            objectKind = MemoryPredicateDefinition.ObjectValueKind.ENTITY,
            cardinality = MemoryPredicateDefinition.Cardinality.MULTI,
            temporalPolicy = MemoryPredicateDefinition.TemporalPolicy.STATUS_LIKE,
            conflictPolicy = MemoryPredicateDefinition.ConflictPolicy.COEXIST,
            semanticKinds = setOf(SemanticKind.PREFERENCE, SemanticKind.TECHNICAL_CONFIGURATION),
            profileSync = true,
            defaultImportance = 7,
        ),
        definition(
            predicate = "prefers_framework",
            description = "Preferred framework or library",
            subjectType = MemoryEntity.Type.PERSON,
            objectKind = MemoryPredicateDefinition.ObjectValueKind.ENTITY,
            cardinality = MemoryPredicateDefinition.Cardinality.MULTI,
            temporalPolicy = MemoryPredicateDefinition.TemporalPolicy.STATUS_LIKE,
            conflictPolicy = MemoryPredicateDefinition.ConflictPolicy.COEXIST,
            semanticKinds = setOf(SemanticKind.PREFERENCE, SemanticKind.TECHNICAL_CONFIGURATION),
            profileSync = true,
            defaultImportance = 6,
        ),
    )

    private fun definition(
        predicate: String,
        description: String,
        subjectType: MemoryEntity.Type? = null,
        objectKind: MemoryPredicateDefinition.ObjectValueKind,
        cardinality: MemoryPredicateDefinition.Cardinality,
        temporalPolicy: MemoryPredicateDefinition.TemporalPolicy,
        conflictPolicy: MemoryPredicateDefinition.ConflictPolicy,
        semanticKinds: Set<MemoryPredicateDefinition.SemanticKind>,
        aggregateEffect: MemoryPredicateDefinition.AggregateEffect = MemoryPredicateDefinition.AggregateEffect.NONE,
        profileSync: Boolean = false,
        actionItemSync: Boolean = false,
        defaultImportance: Int,
    ): MemoryPredicateDefinition =
        MemoryPredicateDefinition(
            predicate = predicate,
            description = description,
            subjectType = subjectType,
            objectKind = objectKind,
            cardinality = cardinality,
            temporalPolicy = temporalPolicy,
            conflictPolicy = conflictPolicy,
            semanticKinds = semanticKinds,
            aggregateEffect = aggregateEffect,
            profileSync = profileSync,
            actionItemSync = actionItemSync,
            defaultImportance = defaultImportance,
        )
}

fun MemoryPredicateCatalog.resolvePredicateDefinition(
    predicate: String?,
    family: String? = null,
): MemoryPredicateDefinition? {
    val names = listOfNotNull(predicate, family)
        .map { it.trim() }
        .filter { it.isNotBlank() && it != "null" }
        .map { it.lowercase() }
    if (names.isEmpty()) return null

    return activeDefinitions()
        .firstOrNull { definition -> names.any { it == definition.predicate.lowercase() } }
}

fun MemoryPredicateCatalog.activeDefinitions(): MemoryPredicateCatalog =
    filter { it.active }
        .distinctBy { it.predicate.lowercase() }
        .sortedBy { it.predicate }
