package com.gromozeka.domain.model.memory

object MemoryPredicateCatalogDefaults {
    fun forNamespace(namespace: MemoryNamespace): MemoryPredicateCatalog =
        definitions.map { it.scopedTo(namespace) }

    private val definitions = listOf(
        definition(
            predicate = "preferred_name",
            description = "Preferred display name for the subject",
            subjectType = MemoryEntity.Type.PERSON,
            objectKind = MemoryPredicateDefinition.ObjectValueKind.STRING,
            cardinality = MemoryPredicateDefinition.Cardinality.SINGLE,
            temporalPolicy = MemoryPredicateDefinition.TemporalPolicy.ATEMPORAL,
            conflictPolicy = MemoryPredicateDefinition.ConflictPolicy.REPLACE,
            profileSync = true,
            defaultImportance = 8,
        ),
        definition(
            predicate = "speaks_language",
            description = "Language known or used by the subject",
            subjectType = MemoryEntity.Type.PERSON,
            objectKind = MemoryPredicateDefinition.ObjectValueKind.STRING,
            cardinality = MemoryPredicateDefinition.Cardinality.MULTI,
            temporalPolicy = MemoryPredicateDefinition.TemporalPolicy.ATEMPORAL,
            conflictPolicy = MemoryPredicateDefinition.ConflictPolicy.COEXIST,
            profileSync = true,
            defaultImportance = 7,
        ),
        definition(
            predicate = "timezone",
            description = "Timezone of the subject",
            subjectType = MemoryEntity.Type.PERSON,
            objectKind = MemoryPredicateDefinition.ObjectValueKind.STRING,
            cardinality = MemoryPredicateDefinition.Cardinality.SINGLE,
            temporalPolicy = MemoryPredicateDefinition.TemporalPolicy.STATUS_LIKE,
            conflictPolicy = MemoryPredicateDefinition.ConflictPolicy.REPLACE,
            profileSync = true,
            defaultImportance = 7,
        ),
        definition(
            predicate = "prefers_response_language",
            description = "Preferred language for assistant responses",
            subjectType = MemoryEntity.Type.PERSON,
            objectKind = MemoryPredicateDefinition.ObjectValueKind.STRING,
            cardinality = MemoryPredicateDefinition.Cardinality.SINGLE,
            temporalPolicy = MemoryPredicateDefinition.TemporalPolicy.STATUS_LIKE,
            conflictPolicy = MemoryPredicateDefinition.ConflictPolicy.REPLACE,
            profileSync = true,
            defaultImportance = 9,
        ),
        definition(
            predicate = "prefers_answer_detail",
            description = "Preferred answer detail level",
            subjectType = MemoryEntity.Type.PERSON,
            objectKind = MemoryPredicateDefinition.ObjectValueKind.STRING,
            cardinality = MemoryPredicateDefinition.Cardinality.SINGLE,
            temporalPolicy = MemoryPredicateDefinition.TemporalPolicy.STATUS_LIKE,
            conflictPolicy = MemoryPredicateDefinition.ConflictPolicy.REPLACE,
            profileSync = true,
            defaultImportance = 8,
        ),
        definition(
            predicate = "prefers_tone",
            description = "Preferred response tone",
            subjectType = MemoryEntity.Type.PERSON,
            objectKind = MemoryPredicateDefinition.ObjectValueKind.STRING,
            cardinality = MemoryPredicateDefinition.Cardinality.SINGLE,
            temporalPolicy = MemoryPredicateDefinition.TemporalPolicy.STATUS_LIKE,
            conflictPolicy = MemoryPredicateDefinition.ConflictPolicy.REPLACE,
            profileSync = true,
            defaultImportance = 7,
        ),
        definition(
            predicate = "prefers_code_comment_language",
            description = "Preferred language for code comments",
            subjectType = MemoryEntity.Type.PERSON,
            objectKind = MemoryPredicateDefinition.ObjectValueKind.STRING,
            cardinality = MemoryPredicateDefinition.Cardinality.SINGLE,
            temporalPolicy = MemoryPredicateDefinition.TemporalPolicy.STATUS_LIKE,
            conflictPolicy = MemoryPredicateDefinition.ConflictPolicy.REPLACE,
            profileSync = true,
            defaultImportance = 9,
        ),
        definition(
            predicate = "works_with",
            description = "Current or ongoing technology/tool usage",
            subjectType = MemoryEntity.Type.PERSON,
            objectKind = MemoryPredicateDefinition.ObjectValueKind.ENTITY,
            cardinality = MemoryPredicateDefinition.Cardinality.MULTI,
            temporalPolicy = MemoryPredicateDefinition.TemporalPolicy.STATUS_LIKE,
            conflictPolicy = MemoryPredicateDefinition.ConflictPolicy.COEXIST,
            profileSync = true,
            defaultImportance = 7,
        ),
        definition(
            predicate = "prefers",
            description = "Generic positive preference when no named current/default/primary/chosen slot predicate is more precise",
            subjectType = MemoryEntity.Type.PERSON,
            objectKind = MemoryPredicateDefinition.ObjectValueKind.ENTITY,
            cardinality = MemoryPredicateDefinition.Cardinality.MULTI,
            temporalPolicy = MemoryPredicateDefinition.TemporalPolicy.STATUS_LIKE,
            conflictPolicy = MemoryPredicateDefinition.ConflictPolicy.COEXIST,
            profileSync = true,
            defaultImportance = 7,
        ),
        definition(
            predicate = "avoids",
            description = "Negative preference, exclusion, or avoid instruction",
            objectKind = MemoryPredicateDefinition.ObjectValueKind.ENTITY,
            cardinality = MemoryPredicateDefinition.Cardinality.MULTI,
            temporalPolicy = MemoryPredicateDefinition.TemporalPolicy.STATUS_LIKE,
            conflictPolicy = MemoryPredicateDefinition.ConflictPolicy.COEXIST,
            profileSync = true,
            defaultImportance = 7,
        ),
        definition(
            predicate = "believes",
            description = "Attributed belief, opinion, or viewpoint held by the subject",
            objectKind = MemoryPredicateDefinition.ObjectValueKind.STRING,
            cardinality = MemoryPredicateDefinition.Cardinality.MULTI,
            temporalPolicy = MemoryPredicateDefinition.TemporalPolicy.STATUS_LIKE,
            conflictPolicy = MemoryPredicateDefinition.ConflictPolicy.COEXIST,
            defaultImportance = 7,
        ),
        definition(
            predicate = "has_experience_with",
            description = "Experience with a technology or domain",
            subjectType = MemoryEntity.Type.PERSON,
            objectKind = MemoryPredicateDefinition.ObjectValueKind.ENTITY,
            cardinality = MemoryPredicateDefinition.Cardinality.MULTI,
            temporalPolicy = MemoryPredicateDefinition.TemporalPolicy.ATEMPORAL,
            conflictPolicy = MemoryPredicateDefinition.ConflictPolicy.COEXIST,
            profileSync = true,
            defaultImportance = 6,
        ),
        definition(
            predicate = "has_goal",
            description = "Active or declared goal",
            objectKind = MemoryPredicateDefinition.ObjectValueKind.STRING,
            cardinality = MemoryPredicateDefinition.Cardinality.MULTI,
            temporalPolicy = MemoryPredicateDefinition.TemporalPolicy.STATUS_LIKE,
            conflictPolicy = MemoryPredicateDefinition.ConflictPolicy.COEXIST,
            profileSync = true,
            taskSync = true,
            defaultImportance = 8,
        ),
        definition(
            predicate = "has_constraint",
            description = "Stable user or project constraint",
            objectKind = MemoryPredicateDefinition.ObjectValueKind.STRING,
            cardinality = MemoryPredicateDefinition.Cardinality.MULTI,
            temporalPolicy = MemoryPredicateDefinition.TemporalPolicy.STATUS_LIKE,
            conflictPolicy = MemoryPredicateDefinition.ConflictPolicy.COEXIST,
            profileSync = true,
            defaultImportance = 8,
        ),
        definition(
            predicate = "responsible_for",
            description = "Subject owns or is responsible for a workstream, component, process, account duty, or operational area",
            objectKind = MemoryPredicateDefinition.ObjectValueKind.ENTITY,
            cardinality = MemoryPredicateDefinition.Cardinality.MULTI,
            temporalPolicy = MemoryPredicateDefinition.TemporalPolicy.STATUS_LIKE,
            conflictPolicy = MemoryPredicateDefinition.ConflictPolicy.COEXIST,
            profileSync = true,
            defaultImportance = 8,
        ),
        definition(
            predicate = "works_on_project",
            description = "Association with a project when no more specific role, responsibility, ownership, or project-state predicate is available",
            subjectType = MemoryEntity.Type.PERSON,
            objectKind = MemoryPredicateDefinition.ObjectValueKind.ENTITY,
            cardinality = MemoryPredicateDefinition.Cardinality.MULTI,
            temporalPolicy = MemoryPredicateDefinition.TemporalPolicy.TIME_SCOPED,
            conflictPolicy = MemoryPredicateDefinition.ConflictPolicy.RANGE_SPLIT,
            profileSync = true,
            taskSync = true,
            defaultImportance = 7,
        ),
        definition(
            predicate = "primary_storage_backend",
            description = "Primary storage or persistence backend for a project or service",
            subjectType = MemoryEntity.Type.PROJECT,
            objectKind = MemoryPredicateDefinition.ObjectValueKind.ENTITY,
            cardinality = MemoryPredicateDefinition.Cardinality.SINGLE,
            temporalPolicy = MemoryPredicateDefinition.TemporalPolicy.STATUS_LIKE,
            conflictPolicy = MemoryPredicateDefinition.ConflictPolicy.REPLACE,
            defaultImportance = 8,
        ),
        definition(
            predicate = "uses_search_backend",
            description = "Search backend used by a project or service in a specific environment, phase, or time window",
            objectKind = MemoryPredicateDefinition.ObjectValueKind.ENTITY,
            cardinality = MemoryPredicateDefinition.Cardinality.SINGLE,
            temporalPolicy = MemoryPredicateDefinition.TemporalPolicy.TIME_SCOPED,
            conflictPolicy = MemoryPredicateDefinition.ConflictPolicy.RANGE_SPLIT,
            defaultImportance = 7,
        ),
        definition(
            predicate = "uses_persistence_database",
            description = "Persistence database used by a project or service in a specific environment, phase, or time window",
            subjectType = MemoryEntity.Type.PROJECT,
            objectKind = MemoryPredicateDefinition.ObjectValueKind.ENTITY,
            cardinality = MemoryPredicateDefinition.Cardinality.MULTI,
            temporalPolicy = MemoryPredicateDefinition.TemporalPolicy.TIME_SCOPED,
            conflictPolicy = MemoryPredicateDefinition.ConflictPolicy.RANGE_SPLIT,
            defaultImportance = 6,
        ),
        definition(
            predicate = "owns_vehicle",
            description = "Vehicle owned or used by the subject",
            subjectType = MemoryEntity.Type.PERSON,
            objectKind = MemoryPredicateDefinition.ObjectValueKind.ENTITY,
            cardinality = MemoryPredicateDefinition.Cardinality.MULTI,
            temporalPolicy = MemoryPredicateDefinition.TemporalPolicy.STATUS_LIKE,
            conflictPolicy = MemoryPredicateDefinition.ConflictPolicy.COEXIST,
            profileSync = true,
            defaultImportance = 6,
        ),
        definition(
            predicate = "prefers_storage",
            description = "Preferred storage solution",
            subjectType = MemoryEntity.Type.PERSON,
            objectKind = MemoryPredicateDefinition.ObjectValueKind.ENTITY,
            cardinality = MemoryPredicateDefinition.Cardinality.MULTI,
            temporalPolicy = MemoryPredicateDefinition.TemporalPolicy.STATUS_LIKE,
            conflictPolicy = MemoryPredicateDefinition.ConflictPolicy.COEXIST,
            profileSync = true,
            defaultImportance = 7,
        ),
        definition(
            predicate = "prefers_framework",
            description = "Preferred framework or library",
            subjectType = MemoryEntity.Type.PERSON,
            objectKind = MemoryPredicateDefinition.ObjectValueKind.ENTITY,
            cardinality = MemoryPredicateDefinition.Cardinality.MULTI,
            temporalPolicy = MemoryPredicateDefinition.TemporalPolicy.STATUS_LIKE,
            conflictPolicy = MemoryPredicateDefinition.ConflictPolicy.COEXIST,
            profileSync = true,
            defaultImportance = 6,
        ),
    )

    private fun definition(
        predicate: String,
        description: String,
        subjectType: MemoryEntity.Type? = null,
        objectKind: MemoryPredicateDefinition.ObjectValueKind,
        cardinality: MemoryPredicateDefinition.Cardinality,
        temporalPolicy: MemoryPredicateDefinition.TemporalPolicy,
        conflictPolicy: MemoryPredicateDefinition.ConflictPolicy,
        profileSync: Boolean = false,
        taskSync: Boolean = false,
        defaultImportance: Int,
    ): MemoryPredicateDefinition =
        MemoryPredicateDefinition(
            predicate = predicate,
            description = description,
            subjectType = subjectType,
            objectKind = objectKind,
            cardinality = cardinality,
            temporalPolicy = temporalPolicy,
            conflictPolicy = conflictPolicy,
            profileSync = profileSync,
            taskSync = taskSync,
            defaultImportance = defaultImportance,
        )
}

fun MemoryPredicateCatalog.resolvePredicateDefinition(
    predicate: String?,
    family: String? = null,
): MemoryPredicateDefinition? {
    val names = listOfNotNull(predicate, family)
        .map { it.trim() }
        .filter { it.isNotBlank() && it != "null" }
        .map { it.lowercase() }
    if (names.isEmpty()) return null

    return activeDefinitions()
        .firstOrNull { definition -> names.any { it == definition.predicate.lowercase() } }
}

fun MemoryPredicateCatalog.activeDefinitions(): MemoryPredicateCatalog =
    filter { it.active }
        .distinctBy { it.predicate.lowercase() }
        .sortedBy { it.predicate }
