package com.gromozeka.bot.domain.model.memory

import kotlinx.datetime.Instant

/**
 * Entity node in the knowledge graph representing a named concept or object.
 *
 * Knowledge graph stores facts as entity-relationship triples: (Entity)-[Relationship]->(Entity).
 * This class represents entity nodes with semantic embeddings for similarity search.
 *
 * ## Multi-tenancy
 * Entities are isolated by [groupId] to support multiple users/contexts.
 *
 * ## Semantic Search
 * [embedding] enables vector similarity search for finding related entities.
 * Embeddings are generated from entity name using text-embedding-3-large (3072 dimensions).
 *
 * This is an immutable value type - use copy() to create modified versions.
 *
 * @property uuid unique entity identifier (UUIDv4)
 * @property name entity name (e.g., "Gromozeka", "Kotlin", "Clean Architecture")
 * @property embedding vector representation of entity name for semantic search (3072 dimensions, nullable if not yet embedded)
 * @property summary human-readable description of the entity (generated by LLM, max ~250 chars)
 * @property groupId multi-tenancy identifier isolating entities per user/context (currently "dev-user")
 * @property labels entity type labels from entity-types.json (e.g., ["Technology"], ["Person"], ["Concept"])
 * @property createdAt timestamp when entity was created
 * @property attributes extensible key-value storage for future metadata (currently unused)
 */
data class MemoryObject(
    val uuid: String,
    val name: String,
    val embedding: List<Float>?,
    val summary: String,
    val groupId: String,
    val labels: List<String>,
    val createdAt: Instant,
    val attributes: Map<String, Any> = emptyMap()
)
