@startuml
box "Local Machine"
  actor User
  participant ChatApp
  participant MCP

end box

box "Internet"
  participant LLM
end box


group Common flow
User -> ChatApp : sends message
ChatApp -> LLM : forwards message
LLM -> ChatApp : returns response
ChatApp -> User : displays response
end


group MCP init
User -> ChatApp : opens app
ChatApp -> MCP : queries available tools
MCP -> ChatApp : returns available tools
ChatApp -> LLM : informs about MCP availability
end

group MCP messaging
User -> ChatApp : sends message
ChatApp -> LLM : forwards message

loop while tools are required
  LLM -> ChatApp : mcp tool call request
  ChatApp -> MCP : call tool
  MCP -> ChatApp : tool result
  ChatApp -> LLM : forwards result
end

LLM -> ChatApp : send response
ChatApp -> User : displays response
end

@enduml
