package com.gromozeka.application.service.memory

internal object MemoryReadPromptPolicy {
    fun selectorCountAndCategoryRules(): String =
        """
        - For count, list, "how many", and COMPLETE_SET questions, do not require exact target wording. Select plausible action, lifecycle, ownership, ordering, delivery, repair, completion, attendance, and status variants when they may contribute a separate answer item.
        - For aggregate total/count questions, when compatible metric_observation, current_metric_value, or other explicit numeric aggregate candidates are available, treat those numeric operands as the counted inventory. Reject separate singular POSSESSION or owns candidates unless the candidate explicitly says the singular item belongs to the same counted aggregate and is not already covered by a numeric operand.
        - For increase, decrease, change, delta, difference, gain, loss, or net-movement questions, keep compatible baseline/previous and later/current/final numeric operands for the same metric or aggregate. A baseline operand is relevant even when it is not the final value; rejecting it can make the arithmetic impossible.
        - For historical aggregate totals across metric_observation candidates, keep every distinct observed operand. Do not collapse two metric_observation candidates merely because they share the same named subject; different attempt, event, condition, session, source, date, difficulty, route, measurement context, or wording can be separate operands. Reject one as duplicate only when it is the same measurement slot or the memory explicitly says it corrects, replaces, retracts, or repeats the other.
        - Apply latest/current-value replacement logic to current_metric_value candidates, not to independent metric_observation candidates. A newer metric_observation does not make an older metric_observation stale by itself.
        - For imported-source events with an explicit month/day but no explicit year, past-tense wording, and a same-year normalization that would put the event after the source or question date, treat the inferred year as uncertain. For relative-window aggregate/count questions, keep otherwise matching explicit numeric operands instead of rejecting them solely as future or outside-window.
        - For relative month-window questions over imported chat sources, a first-person source-local cue such as "last month" can satisfy the requested month window when the source/session date is close to the question date and no explicit date places the event outside the window. Do not reject it solely because the exact day inside that relative month is unknown.
        - For project leadership, ownership, or responsibility count/list questions, select explicit responsible_for, lead/led/managed/owned, team-leadership, solo-project, or user-owned-project candidates. Treat plain works_on_project, generic project association, research topic, paper, poster, broad interest, "my research", or "working on research" candidates as supporting or exclusion context unless they explicitly say the user owns, leads, is responsible for, or is the sole actor on that project.
        - For count/list questions about acquired, kept, used, completed, attended, or otherwise user-attributed items, keep evidence-backed variants that may satisfy the requested category even when the source uses a different lifecycle or status verb than the question. Require explicit user attribution and category fit; do not keep merely adjacent examples.
        - For use-scoped count/list questions, keep candidates only when retrieved memory places the item inside the user's actual use or adoption in the requested scope. Treat assistant recommendations, option lists, examples, hypothetical possibilities, and merely discussed components as non-evidence unless selected memory says the user adopted, made, served, prepared, used, or chose that item or a containing artifact for the requested scope.
        - For count/list questions scoped before, prior to, until, or at a commitment/decision about a named target, keep the named target as boundary context but do not treat it as a prior alternative/item unless the question explicitly asks to include the target itself. This remains true even when the named target has its own matching action before the boundary event.
        - For replaced/fixed/upgraded functional-slot counts, keep paired evidence that an old item was removed, discarded, donated, given away, or got rid of and a new item or upgrade took over the same ordinary function. The new item's source, such as gift, purchase, or existing ownership, is not an exclusion reason by itself.
        - For indirect replacement/upgrade evidence, keep both sides of the functional slot when memory connects a newly acquired, gifted, bought, adopted, or started-using item with removal, donation, give-away, or discard of an older same-role item, even when the source does not use the exact word "replace".
        - Treat successor or substitute items as same-role when they serve the same ordinary user function or routine, even if their exact subtype differs. A same-source/session pattern of "newer or more capable item introduced for a routine" plus "older same-domain item removed from inventory" is relevant replacement/upgrade evidence unless memory explicitly says the items are unrelated.
        - For acquisition-style count/list questions, keep concrete physical or digital items when memory places that item in the user's acquisition, possession, collection, or use history and the requested category fits. Do not require the exact action verb from the question; reject mere mentions, interests, recommendations, or assistant-only suggestions.
        - For acquisition-style count/list questions, POSSESSION semantic claims are strong typed evidence when the possessed item fits the requested category.
        - For acquisition-style count/list questions, selected ACTIVE "owns" or POSSESSION claims are direct acquisition/possession evidence when the item fits the requested category. The words purchased, bought, downloaded, acquired, or got in a how-many/list question are lifecycle hints, not transaction-detail requirements by themselves.
        - Explicitly ordered, reserved, or preordered concrete items are acquisition evidence when the requested category fits; pending delivery, receipt, or pickup only excludes the item when the target specifically asks for completed receipt, delivery, pickup, or current possession after a contradictory later status.
        - First-person evidence of a concrete personal copy or item can satisfy an acquisition-style broad category count even without a transaction verb. Keep it unless the question specifically asks for purchase/download transaction details such as price, store, payment, download source, or exact date.
        - Treat "how many X did I buy/download/acquire/get" as a broad category count unless the user asks for transaction details. For broad category counts, do not require exact subtype words or exact title when ordinary language makes the remembered personal item a member, copy, or instance of the requested category.
        - In count/list questions, broad category labels are semantic category-fit tests, not exact-word qualifiers. Do not reject a plausible counted item solely because memory names a member, carrier, copy, component, concrete instance, or ordinary subtype instead of repeating the category label.
        - For broad counts of works or content items, a user-attributed physical or digital carrier, copy, file, license, or collection item can count as the represented work or content item when ordinary language supports that category fit. The material, format, or access method is not a separate category requirement unless the question asks for format-specific or transaction-specific details.
        - For location-scoped item count/list questions, keep concrete objects explicitly placed in that location or whose ordinary function fits that location. Do not narrow a location item category to an arbitrary subtype unless the question says so.
        - For functional category count/list questions, keep concrete objects whose ordinary role, use, or support function satisfies the requested category even when memory names only the concrete subtype. Reject adjacent decor, accessories, optional examples, and suggestions unless they themselves satisfy the requested category or the question asks for them.
        - For broad category counts, a missing exact subtype word is not a contradiction. Exclude a selected user-attributed copy/member/carrier/subtype only when retrieved memory gives an explicit conflicting subtype or category, or when the question asks for exact subtype/transaction details.
        """.trimIndent()

    fun answerCountAndCategoryRules(): String =
        """
            For numeric count/list answers, first form the set of counted items from retrieved memory and make the final number match that set size. If a selected ranked reference is a plausible counted item, include it or explicitly exclude it; do not silently ignore it. An empty counted set is not evidence for zero by itself; answer zero only when retrieved memory explicitly states none/zero for the requested scope or provides a closed complete inventory for that exact scope. Otherwise say memory is insufficient or the requested item was not mentioned, and do not put a concrete zero count in the final answer.
            For project leadership, ownership, or responsibility count/list questions, a plain works_on_project or generic project association claim is not enough by itself. Count explicit responsible_for/lead/led/managed/owned claims, explicit team-leadership evidence, and solo or user-owned project evidence. Count personal/current projects only when retrieved memory says the user owns, leads, is responsible for, or is the sole actor on the project. Exclude research topics, papers, posters, broad interests, and plain "my research" or "working on research" evidence unless leadership, ownership, responsibility, or solo execution is explicit.
            For aggregate total/count questions, count only explicit numeric operands or explicit list items that the retrieved memory places in the requested aggregate. When compatible metric_observation, current_metric_value, or other explicit numeric aggregate operands are selected, they define the counted inventory; do not add separate singular possession or ownership claims as +1 unless memory explicitly states that singular item belongs to the same counted aggregate and is not already covered by a numeric operand. For historical totals across metric_observation items, count every distinct observed operand unless retrieved memory explicitly says one corrects, replaces, retracts, or repeats another same-slot measurement. Different attempt, event, condition, session, source, date, route, difficulty, or measurement context can make same-subject observations separate operands. For current aggregate totals, first find the latest explicit baseline total for the same collection, then apply later explicit additions or removals in chronological order. A direct older current_metric_value is not final when selected later memory explicitly adds or removes an item in the same aggregate.
            For increase, decrease, change, delta, difference, gain, loss, or net-movement questions, compute from compatible explicit numeric operands in retrieved memory. Use a selected baseline/previous value and a selected later/current/final value for the same metric or aggregate even when their scope wording is not identical, as long as retrieved memory does not contradict that they belong to the same measured series. Do not answer "insufficient" solely because the baseline is phrased as an initial/start value and the later value is phrased as an after-period observation.
            For imported-source events with an explicit month/day but no explicit year, past-tense wording, and a same-year normalization that would put the event after the source or question date, treat the inferred year as uncertain. For relative-window aggregate/count questions, count otherwise matching explicit numeric operands instead of excluding them solely as future or outside-window.
            For relative month-window questions over imported chat sources, a first-person source-local cue such as "last month" can satisfy the requested month window when the source/session date is close to the question date and no explicit date places the event outside the window. Do not reject it solely because the exact day inside that relative month is unknown.
            For count/list questions about acquired, kept, used, completed, attended, or otherwise user-attributed items, count evidence-backed variants that satisfy the requested category even when retrieved memory uses a different lifecycle or status verb than the question. Require explicit user attribution and category fit; do not count merely adjacent examples.
            For use-scoped count/list questions, count only items that retrieved memory places inside the user's actual use or adoption in the requested scope. Assistant recommendations, option lists, examples, hypothetical possibilities, and merely discussed components are not counted unless selected memory says the user adopted, made, served, prepared, used, or chose that item or a containing artifact for the requested scope.
            For count/list questions scoped before, prior to, until, or at a commitment/decision about a named target, use the named target as boundary context and exclude the target itself from the prior-alternative counted set unless the question explicitly asks to include the target itself. This remains true even when the named target has its own matching action before the boundary event. Put the target in the excluded set as the boundary target, not in the counted set.
            For replaced/fixed/upgraded functional-slot counts, count paired evidence that an old item was removed, discarded, donated, given away, or got rid of and a new item or upgrade took over the same ordinary function. The new item's source, such as gift, purchase, or existing ownership, is not an exclusion reason by itself.
            For indirect replacement/upgrade evidence, count one functional slot when memory connects a newly acquired, gifted, bought, adopted, or started-using item with removal, donation, give-away, or discard of an older same-role item, even when the source does not use the exact word "replace".
            Treat successor or substitute items as same-role when they serve the same ordinary user function or routine, even if their exact subtype differs. A same-source/session pattern of "newer or more capable item introduced for a routine" plus "older same-domain item removed from inventory" is replacement/upgrade evidence unless memory explicitly says the items are unrelated.
            For acquisition-style count/list questions, count concrete physical or digital items when retrieved memory places that item in the user's acquisition, possession, collection, or use history and the requested category fits. Do not require the exact action verb from the question; do not count mere mentions, interests, recommendations, or assistant-only suggestions.
            For acquisition-style count/list questions, selected ACTIVE "owns" or POSSESSION claims are direct acquisition/possession evidence when the item fits the requested category. The words purchased, bought, downloaded, acquired, or got in a how-many/list question are lifecycle hints, not transaction-detail requirements by themselves.
            Explicitly ordered, reserved, or preordered concrete items are acquisition evidence when the requested category fits; pending delivery, receipt, or pickup only excludes the item when the user specifically asks for completed receipt, delivery, pickup, or current possession after a contradictory later status.
            First-person evidence of a concrete personal copy or item can satisfy an acquisition-style broad category count even without a transaction verb. Do not use this shortcut when the question asks for purchase/download transaction details such as price, store, payment, download source, or exact date.
            Treat "how many X did I buy/download/acquire/get" as a broad category count unless the user asks for transaction details. For broad category counts, do not require exact subtype words or exact title when ordinary language makes the remembered personal item a member, copy, or instance of the requested category.
            In count/list questions, broad category labels are semantic category-fit tests, not exact-word qualifiers. Do not exclude a plausible counted item solely because memory names a member, carrier, copy, component, concrete instance, or ordinary subtype instead of repeating the category label.
            For broad counts of works or content items, a user-attributed physical or digital carrier, copy, file, license, or collection item can count as the represented work or content item when ordinary language supports that category fit. The material, format, or access method is not a separate category requirement unless the question asks for format-specific or transaction-specific details.
            For location-scoped item count/list questions, count concrete objects explicitly placed in that location or whose ordinary function fits that location. Do not narrow a location item category to an arbitrary subtype unless the user says so.
            For functional category count/list questions, count concrete objects whose ordinary role, use, or support function satisfies the requested category even when retrieved memory names only the concrete subtype. Exclude adjacent decor, accessories, optional examples, and suggestions unless they themselves satisfy the requested category or the user asks for them.
            For broad category counts, a missing exact subtype word is not a contradiction. Exclude a selected user-attributed copy/member/carrier/subtype only when retrieved memory gives an explicit conflicting subtype or category, or when the question asks for exact subtype/transaction details.
        """.trimIndent()

    fun answerSourceEvidenceRules(): String =
        """
            Treat a selected source transcript or document as a coherent local evidence frame. If selected typed memory identifies the asked event/item but lacks one requested detail, and selected source evidence gives that detail in the same local topic or surrounding exchange, answer from that same-source frame.
            For source transcripts, preserve local dialogue topic continuity: when the user reports the asked action as an example while the surrounding turns are about a named store, app, service, venue, program, or source, and no competing named frame is introduced before the topic changes, that named frame can supply the missing place/source/medium for the action.
            Do not use this to stitch together different sources, different named targets, different events/items, or competing anchors/values. If the source only mentions a related topic without preserving the same asked target, answer insufficient.
        """.trimIndent()

    fun answerDerivationAndConsistencyRules(): String =
        """
            For ordering, first/second/latest/earliest, and comparison questions, compare every selected dated or relative-time candidate for the named alternatives before choosing the answer. The final answer must be the item selected by that comparison, not the first lexical match or the most recent evidence block.
            For latest/most-recent questions about when the user started, began, first used, acquired, or got access to something, compare actual lifecycle/use/acquisition events for that requested kind. A later recommendation, preference, choice, or access-path decision is not a later started-using event unless selected memory explicitly says the user actually started, used, acquired, or got access to that option.
            For chained relative-time, date-difference, duration, and lead-time questions, identify each operand in reasoning before answering: target event time, anchor event time, source/question date, offsets such as "three months in advance", and elapsed intervals such as "two months ago". A lead time such as "three months in advance" or "two weeks before" is not itself an "ago" answer unless its anchor is the question/current date. When the question asks how long ago the target happened and selected memory gives a lead time before or in advance of another event, first find that anchor event's timing relative to the question/current date, then add or otherwise combine the lead-time offset with the anchor elapsed time. If the anchor timing is not selected, set sufficiency to insufficient instead of returning the lead time as the elapsed answer. Put the arithmetic or combination explicitly in reasoning, then copy the final elapsed value into answer.
            If reasoning compares alternatives or computes a value, end reasoning with the computed final conclusion and copy that same value into answer. Never return an answer field that contradicts the reasoning conclusion. If selected memory does not contain every named operand needed for the comparison or calculation, set sufficiency to insufficient instead of guessing from a partial operand.
        """.trimIndent()
}
