package com.gromozeka.application.service.memory

internal object MemoryLlmStageLimits {
    private const val MEMORY_STAGE_OUTPUT = 64_000

    const val READ_PLANNER_OUTPUT = MEMORY_STAGE_OUTPUT
    const val READ_NEED_VERIFIER_OUTPUT = MEMORY_STAGE_OUTPUT
    const val READ_SELECTOR_OUTPUT = MEMORY_STAGE_OUTPUT
    const val READ_ANSWER_OUTPUT = MEMORY_STAGE_OUTPUT
    const val WRITE_ROUTER_OUTPUT = MEMORY_STAGE_OUTPUT
    const val WRITE_RETRIEVAL_PLANNER_OUTPUT = MEMORY_STAGE_OUTPUT
    const val ENTITY_CANONICALIZER_OUTPUT = MEMORY_STAGE_OUTPUT
    const val NOTE_CONSTRUCTOR_OUTPUT = MEMORY_STAGE_OUTPUT
    const val NOTE_RECONCILER_OUTPUT = MEMORY_STAGE_OUTPUT
    const val CLAIM_EXTRACTOR_OUTPUT = MEMORY_STAGE_OUTPUT
    const val CLAIM_RECONCILER_OUTPUT = MEMORY_STAGE_OUTPUT
    const val ACTION_ITEM_UPDATER_OUTPUT = MEMORY_STAGE_OUTPUT
    const val FORGET_PLANNER_OUTPUT = MEMORY_STAGE_OUTPUT
    const val REPAIR_PLANNER_OUTPUT = MEMORY_STAGE_OUTPUT
    const val ENTITY_MAINTENANCE_PLANNER_OUTPUT = MEMORY_STAGE_OUTPUT
    const val NOTE_CONSOLIDATOR_OUTPUT = MEMORY_STAGE_OUTPUT
    const val THREAD_CONTEXT_COMPACTION_OUTPUT = MEMORY_STAGE_OUTPUT
    const val INGEST_PLANNER_OUTPUT = MEMORY_STAGE_OUTPUT

    const val NOTE_RECONCILER_CANDIDATE_BATCH_SIZE = 8
    const val CLAIM_RECONCILER_CANDIDATE_BATCH_SIZE = 16
}
