services:
  mongodb:
    image: mongo:8.0
    container_name: gromozeka-dev-mongodb
    ports:
      - "27017:27017"
    volumes:
      - ${GROMOZEKA_HOME:-../../../../dev-data/client/.gromozeka}/mongo:/data/db
