# Gromozeka Default Settings Template
# Copy this file to settings.json and modify as needed

# TTS (Text-to-Speech) Configuration
enableTts: true
ttsSpeed: 1.0  # Speech rate: 0.25 (slowest) to 4.0 (fastest), 1.0 = normal speed

# STT (Speech-to-Text) Configuration
enableStt: true
sttMainLanguage: "en"  # Language code - supports ISO 639-1 (e.g., "en", "ru") and 639-3 codes for GPT-4o models

# Voice Control Settings
autoSend: true
globalPttHotkeyEnabled: false
muteSystemAudioDuringPTT: true

# Claude Model Configuration
claudeModel: "sonnet"

# UI Settings
showOriginalJson: false

# System Settings
includeCurrentTime: true
